name: el_poke
description: llamada api Pokemon

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  hooks_riverpod: ^1.0.0-dev.4
  flutter_hooks: ^0.18.0
  freezed: ^0.14.2
  fpdart: ^0.0.7 


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed_annotation: ^0.14.2
  build_runner: ^2.0.5

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

